version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-futebol
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: futebol_db
      MYSQL_USER: futebol_user
      MYSQL_PASSWORD: futebol123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
